version: 0.0.1.{build}-test

# Use default image unless needed
#os:
#- Windows Server 2012 R2

shallow_clone: true

environment:
  LUAROCKS_VER: 2.4.1
  matrix:
  - LUA_VER: 5.1.5
  - LUA_VER: 5.2.4  # Lua 5.2.4 with compatibility flags enabled (DLUA_COMPAT_ALL).
  - LUA_VER: 5.2.4  # Lua 5.2.4 with compatibility flags disabled.
    NOCOMPAT: true
  - LUA_VER: 5.3.2  # Lua 5.3.2 with compatibility flags enabled (DLUA_COMPAT_5_2).
  - LUA_VER: 5.3.2  # Lua 5.3.2 with compatibility flags disabled.
    NOCOMPAT: true
  - LJ_VER: 2.0.4
  - LJ_VER: 2.1

matrix:
  allow_failures:
    - configuration: 2010
      platform: x64
    - configuration: 2008
      platform: x64
    - configuration: MinGW
      platform: x64

# Abuse this section so we can have a matrix with different Compiler versions
# Is there a better way? Like injecting an array in the matrix?
configuration:
  - 2015
  - 2013
  - 2012
  - MinGW
  - 2010 # only works for x86
  - 2008 # only works for x86

platform:
  - x86
  - x64

cache:
  - c:\lua -> appveyor.yml
  - c:\external -> appveyor.yml

# Skip unsupported combinations (ie, VS2008 for x64 is not supported)
init:
- if "%platform%" EQU "x64" ( for %%a in (2008 2010 MinGW) do ( if "%Configuration%"=="%%a" (echo "Skipping unsupported configuration" && exit /b 1 ) ) )


install:
# Make compiler command line tools available
- call .appveyor\set_compiler_env.bat
# Setup Lua development/build environment
- call .appveyor\install.bat

before_build:
# @todo
- echo "Installing external deps"

build_script:
- luarocks make rockspecs/foo-scm-0.rockspec --local

before_test:
# install test only deps (if not already installed)
- luarocks show busted || luarocks install busted
- luarocks show luacov || luarocks install luacov
- luarocks show luacheck || luarocks install luacheck

test_script:
- echo "Testing..."
- luacheck --std max+busted src spec
- busted --verbose --coverage

after_test:
  - if "%LUA_VER:~0,3%"=="5.1" (luarocks show bit32 || luarocks install bit32)
  - luarocks show luacov-coveralls || luarocks install luacov-coveralls
  - luacov-coveralls -v -e c:\lua -c spec\.luacov
